
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module EE314exp1(

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



    // Instantiate ALU with W=4
    ALU #(.W(8)) alu (
        .A(SW[3:0]),        // Operand A from SW[3:0]
        .B(SW[7:4]),        // Operand B from SW[7:4]
        .control(SW[9:8]),  // 2-bit control from SW[9:8]
        .OUT(LEDR[3:0]),    // Result on LEDR[3:0]
        .CO(LEDR[4]),       // Carry Out on LEDR[4]
        .OVF(LEDR[5]),      // Overflow on LEDR[5]
        .N(LEDR[6]),        // Negative on LEDR[6]
        .Z(LEDR[7])         // Zero on LEDR[7]
    );

    // Turn off HEX displays
    assign {HEX0, HEX1, HEX2, HEX3, HEX4, HEX5} = {6{7'b1111111}};
    
    // Unused LEDs
    assign LEDR[9:8] = 2'b00;
endmodule